# Generated by Django 4.0.6 on 2022-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='mainFlower1_amount',
            field=models.IntegerField(),
        ),
    ]
