# Generated by Django 4.0.6 on 2022-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cart_mainflower1_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers1_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers2_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower1_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower2_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower3_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower1_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower2_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower3_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
