# Generated by Django 4.0.6 on 2022-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_cart_bunchofflowers1_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers1_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers2_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower1_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower2_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower3_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower1_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower2_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower3_amount',
            field=models.IntegerField(null=True),
        ),
    ]
